### ISSUE TITLE
v0.2.1 failed to check archive integrity

### ISSUE THREAD

**Issue by mccw** [dariopb/traefikServiceFabricPlugin#5]
error: 
traefik.go:81: command traefik.exe error: failed to check archive integrity of the plugin github.com/dariopb/traefikServiceFabricPlugin: plugin integrity check failed

```
pilot:
    token: "*"
experimental:
  plugins:
    traefikServiceFabricPlugin:
      moduleName: github.com/dariopb/traefikServiceFabricPlugin
      version: v0.2.1

providers:
  file:
    filename: "dyn.yml"

  plugin:
    traefikServiceFabricPlugin:
      pollInterval: 4s
      clusterMangementURL: "https://localhost:19080"
```

I'm using the latest version of Traefik.exe: v2.5.3
If I change the version to v0.1.1 it gets past this error.
